Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Contact
    {
        [Display(Name="Введите имя")]
        [Required(ErrorMessage ="Необходимо ввести имя")]
        public string Name { get; set; }

        [Display(Name = "Введите фамилию")]
        [Required(ErrorMessage = "Необходимо ввести фамилию")]
        public string Surname { get; set; }

        [Display(Name = "Введите возраст")]
        [Required(ErrorMessage = "Необходимо ввести возраст")]
        public int Age { get; set; }

        [Display(Name = "Введите почту")]
        [Required(ErrorMessage = "Необходимо ввести почту")]
        public string Email { get; set; }

        [Display(Name = "Введите сообщение")]
        [Required(ErrorMessage = "Необходимо ввести сообщение")]
        [StringLength(30, ErrorMessage= "Текст не менее 30 символов")]  
        public string Message { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()//Contacts
        {
            return View();
        }

        [HttpPost]
        public IActionResult Check(Contact contact)//Contacts
        {
            if (ModelState.IsValid)
            {
                return Redirect("/");
            }
            return View("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contacts/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Обратная связь";
}

<h1>Обратная связь</h1>

<form method="post" asp-controller="Contacts" asp-action="Check">
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>

    <label asp-for="Surname"></label>
    <input asp-for="Surname" />
    <span asp-validation-for="Surname"></span>

    <label asp-for="Age"></label>
    <input asp-for="Age" />
    <span asp-validation-for="Age"></span>

    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email"></span>

    <label asp-for="Message"></label>
    <input asp-for="Message" />
    <span asp-validation-for="Message"></span>

    <input type="submit" value="Отправить" />
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница сайта";
}

<h1>Главная страница сайта</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <span class="logo">GROWL<img src="sova.jpg" alt="Image Error" /></span>
        <nav>
            <a href = "/">Главная</a>
            <a href="contacts">Обратная связь</a>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>Все права защищены</footer>
</body>
</html>